export const SET_INITIAL_GAME_STATE = "SET_INITIAL_GAME_STATE",
  DRAW_CARDS = "DRAW_CARDS",
  APPLY_STATS_CHANGE = "APPLY_STATS_CHANGE",
  CHANGE_PLAYER = "CHANGE_PLAYER",
  // DISCARD_CARD = "DISCARD_CARD",
  USE_CARD = "USE_CARD",
  DISABLE_CARD = "DISABLE_CARD",
  ENABLE_CARD ="ENABLE_CARD",
  SET_PLAYER_NAME = "SET_PLAYER_NAME"
  
